name: Acceptance Test
description: Describe the acceptance test for this feature or task.
title: "AT "
labels: ["acceptance test"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Acceptance Test!
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature or US.
      placeholder: Describe the criteria here.
      value: |
        - [ ] Criteria 1: Describe the first acceptance criterion here.
        - [ ] Criteria 2: Describe the second acceptance criterion here.
        - [ ] Criteria 3: Describe additional criteria as needed.
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Include any relevant resources, such as a link to the User Story.
      value: "User Story: [Here goes a URL to the corresponding User Story](Link Here)"
    validations:
      required: false
