name: Bug report
description: Create an Issue for a Bug Report
title: "Bug #"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Bug Report!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a brief description of the bug.
      placeholder: Describe the bug here.
      value: "Bug Description"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce The Bug
      description: Provide the steps to reproduce the bug.
      placeholder: List the steps to reproduce the issue here.
      value: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: What Is The Expected Result?
      description: Describe what you expected to happen.
      placeholder: Describe the expected result here.
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: What Is The Actual Result?
      description: Describe what actually happened.
      placeholder: Describe the actual result here.
    validations:
      required: true
  - type: checkboxes
    id: current-strategy
    attributes:
      label: Current Strategy
      description: Choose the strategy for handling this bug.
      options:
        - label: Fix it now
        - label: Fix it later
        - label: Ignore it
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details/Screenshots
      description: Provide any additional context, error messages, or screenshots.
      placeholder: Add any additional details here.
      value: "Additional context, error messages, or screenshots."
    validations:
      required: false
