name: Add Items
description: Add as many items as you need by filling in the fields below.
title: "[Add Items]"

body:
  - type: input
    id: item_1
    attributes:
      description: Provide the first item.
      placeholder: "Enter your first item"
      required: true
