body:
  - type: input
    id: bug_title
    attributes:
      label: Bug Title
      description: Provide a brief title for the bug.
      placeholder: "Enter the bug title"
      required: true  # This is valid because `input` supports `required`.
