name: Security Report
description: Use this template to an issue of security.
title: "[security] "

body:
  - type: markdown
    attributes:
      value: |
        ## Secruty Report
        Please fill out the form below to report a Securty type issue.

  # - type: input
  #   id: bug_title
  #   attributes:
  #     label: Bug Title
  #     description: A brief title for the bug.
  #     placeholder: "Enter a short, descriptive bug title"
  #     required: true  # Valid usage

  # - type: textarea
  #   id: bug_description
  #   attributes:
  #     label: Bug Description
  #     description: Provide a detailed description of the bug.
  #     placeholder: "Describe the issue, steps to reproduce, and expected behavior."
  #     required: true  # Valid usage

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Low
        - Medium
        - High
      # required: true  # Valid usage
