name: Security Report
description: Use this template to report a security-related issue.
title: "[security] "

body:
  - type: markdown
    attributes:
      value: |
        ## Security Report
        Please fill out the form below to report a security-related issue. This will help us prioritize and address security concerns effectively.

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Provide a brief description of the security issue you're reporting.
      placeholder: |
        Describe the vulnerability, exploit, or risk you’ve encountered.
        Include any important details that can help us understand the issue.

  - type: dropdown
    id: security-level
    attributes:
      label: Security Level
      description: How severe is the vulnerability?
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: checkboxes
    id: infected-systems
    attributes:
      label: Infected Systems/Components
      description: Which systems or components are affected by this vulnerability?
      options:
        - label: Frontend/UI
        - label: Backend/API
        - label: Database
        - label: Authentication
        - label: Third-party integrations
        - label: Other (please specify in description)

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Provide any extra context, evidence, or details about the security issue.
      placeholder: |
        Add any relevant details such as logs, screenshots, or other supporting information.
