name: User Story
description: Describe a specific User Story
title: "US #"
labels: ["user story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this User Story!

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Provide the details of the user story.
      placeholder: |
        **As a [role],**
        **I want [an action or feature],**
        **So that [a reason or benefit].**
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this User Story.
      placeholder: |
        - [ ] Criteria 1: Describe the first acceptance criterion here.
        - [ ] Criteria 2: Describe the second acceptance criterion here.
        - [ ] Criteria 3: Describe additional criteria as needed.
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: List the criteria for the user story to be considered "done."
      placeholder: |
        - [ ] All acceptance criteria are met.
        - [ ] Code is reviewed and approved.
        - [ ] Necessary tests are written and pass.
        - [ ] Documentation is updated, if applicable.
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Include any relevant resources, such as mockups or design documents.
      placeholder: "Mockups: [Here goes a URL to or the name of the mockup(s) in inVision]"
    validations:
      required: false
