name: User Story
description: Create an Issue for a User Story
title: "US #"
labels: ["user story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this User Story!

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Provide a description of the user story.
      placeholder: |
        As a [role],
        I want [an action or feature],
        So that [a reason or benefit].
    validations:
      required: true
  - type: dropdown
    id: Priority
    attributes:
      label: Priority Level
      description: What is the Priority of the US?
      options:
        - Low
        - Medium
        - High
        - Critical
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: List the criteria for the user story to be considered "done."
      options: 
        - label: "All acceptance criteria are met."
        - label: "Code is reviewed and approved."
        - label: "Necessary tests are written and pass."
        - label: "Documentation is updated, if applicable."
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Include any relevant resources, such as mockups or design documents.
      placeholder: "Mockups: [Here goes a URL to or the name of the mockup(s) in inVision]"
    validations:
      required: false
