name: EAS Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - production  # Only trigger on push to 'production' branch

jobs:
  build:
    name: Install and Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build on EAS for Android
        run: eas build --platform android --non-interactive --no-wait
