name: CI Pipeline
on:
  push:
    # Runs on all branches
  pull_request:
    # Runs on all PRs
jobs:
  test_and_coverage:
    name: Run Unit Tests & Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --legacy-peer-deps
      - name: Run Jest Tests with Coverage
        run: yarn coverage 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          slug: MiniCapstone-Project/SOEN390

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test_and_coverage  # Ensure Jest & Codecov finish first
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Sonar history
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --legacy-peer-deps
      - name: Run Jest Tests with Coverage (Again for Sonar)
        run: yarn coverage # Use the 'coverage' script from package.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MiniCapstone-Project_SOEN390
            -Dsonar.organization=minicapstone-project
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

