# name: Test and Coverage

# on:
#   push:
#   pull_request:

# jobs:
#   test_and_coverage:
#     name: Run Tests & Upload Coverage
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Restore Jest Coverage Cache
#         uses: actions/cache@v4
#         with:
#           path: ./coverage
#           key: coverage-${{ github.sha }}
#           restore-keys: |
#             coverage-

#       - name: Install dependencies
#         run: npm install --legacy-peer-deps

#       - name: Install Jest
#         run: npm install -g jest

#       - name: Run Tests and Generate Coverage
#         run: jest --coverage

#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v5
#         with:
#           files: ./coverage/lcov.info
#           token: ${{ secrets.CODECOV_TOKEN }}
#           flags: unittests
#           fail_ci_if_error: true
#           slug: MiniCapstone-Project/SOEN390

#       - name: Save Jest Coverage Cache
#         uses: actions/cache@v4
#         with:
#           path: ./coverage
#           key: coverage-${{ github.sha }}-${{ github.run_id }}
#           restore-keys: |
#             coverage-

